server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          #uri:  git@github.com:itwangqingwen/microservicecloud-config.git #github上面的名字
          strict-host-key-checking: false
          uri: https://github.com/itwangqingwen/microservicecloud-config.git

